modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/LegoMaster3650/ItemUpgrader-Core/issues"

[[mods]]
modId="itemupgrader"
version="${file.jarVersion}"
displayName="Item Upgrader Core"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/itemupgrader-core"
logoFile="itemupgrader_core.png"
#credits="Joe Mama"
authors="LegoMaster3650"
displayTest="MATCH_VERSION"
description='''
Core for the Item Upgrader mod, containing the base upgrade system and more generic features
'''

[[dependencies.itemupgrader]]
	modId="forge"
	mandatory=true
	versionRange="[43.1,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemupgrader]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.2,1.20)"
	ordering="NONE"
	side="BOTH"

[modproperties.itemupgrader]
	catalogueImageIcon="itemupgrader_core_small.png"