modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="itemupgrader"
version="${file.jarVersion}"
displayName="Item Upgrader Core"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="itemupgrader.png"
#credits="Joe Mama"
authors="LegoMaster3650"
displayTest="MATCH_VERSION"
description='''
Core for the Item Upgrader mod, containing the base upgrade system and more generic features
'''

[[dependencies.itemupgrader]]
	modId="forge"
	mandatory=true
	versionRange="[43.1,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.itemupgrader]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.2,1.20)"
	ordering="NONE"
	side="BOTH"

[modproperties.itemupgrader]
	catalogueItemIcon="minecraft:smithing_table"